# Site settings
title: "My Technical Blog"
description: "A comprehensive blog about technology, programming, software development, and industry insights. Learn about modern web development, AI, DevOps, and best practices."
author: "Ventsislav Yordanov"
email: "ventsislavy@gilat.com"
url: "https://ventsislavy-g.github.io"
baseurl: ""

# SEO and Social
logo: /assets/images/logo.png
social:
  name: Ventsislav Yordanov
  links:
    - https://github.com/ventsislavy-g
    - https://linkedin.com/in/ventsislav-yordanov

# Social links (for jekyll-seo-tag)
twitter_username: ventsislavy
github_username: ventsislavy-g
linkedin_username: ventsislav-yordanov

# Author information for structured data
author:
  name: "Ventsislav Yordanov"
  bio: "Software Developer passionate about technology, programming, and sharing knowledge through blogging."
  location: "Global"
  urls:
    - https://github.com/ventsislavy-g

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .bundle

# Include files
include:
  - _pages